#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
cd $OPENSHIFT_REPO_DIR
nohup java -jar target/coffeeshop-api-0.0.1-SNAPSHOT.jar server coffeeshop.openshift.yml > ${OPENSHIFT_DIY_LOG_DIR}/coffeeshop.log 2>&1 &
